#!/bin/sh
# Generated by scripts/build-client-installer.mjs; edit client/install.template.sh.
set -eu

default_schedule="17 3 * * *"
server=""
certificate=""
file_specs=""
destination=""
schedule="$default_schedule"
reload_command=""
auto_update=0

usage() {
  cat <<'EOF'
Install a recurring CertVault certificate download.

Usage:
  install.sh --server URL --certificate NAME --destination DIRECTORY [OPTIONS]

The API token is read from CERTVAULT_API_KEY or prompted for securely.

Options:
  --file ARTIFACT[=OUTPUT]
                          Download an artifact, optionally renaming it. Repeatable.
  --auto-update           Check for signed client updates during the same cron job.
                          Requires an HTTPS server URL.
  --schedule CRON        Cron schedule. Defaults to "17 3 * * *".
  --reload-command CMD   Shell command to run after a new bundle is deployed.

Artifacts are certificate.crt, chain.crt, fullchain.crt, and private.key.
Requires Linux with curl, tar, OpenSSL, flock, and GNU mv.
EOF
}

# Parse only simple flags here; file mappings are normalized and validated as a
# complete set below so duplicate artifacts and output names can be rejected.
while [ "$#" -gt 0 ]; do
  case "$1" in
    --server) server=${2-}; shift 2 ;;
    --certificate) certificate=${2-}; shift 2 ;;
    --file)
      spec=${2-}
      file_specs="${file_specs}${file_specs:+,}$spec"
      shift 2
      ;;
    --destination) destination=${2-}; shift 2 ;;
    --schedule) schedule=${2-}; shift 2 ;;
    --reload-command) reload_command=${2-}; shift 2 ;;
    --auto-update) auto_update=1; shift ;;
    --help|-h) usage; exit 0 ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

if [ -z "$server" ] || [ -z "$certificate" ] || [ -z "$destination" ]; then
  usage >&2
  exit 2
fi

if [ "$auto_update" -eq 1 ]; then
  case "$server" in https://*) ;; *) printf 'Client auto-update requires HTTPS\n' >&2; exit 2 ;; esac
fi

# Convert every ARTIFACT[=OUTPUT] value into the explicit ARTIFACT=OUTPUT form
# consumed by the generated sync script. Output names are restricted to
# basenames so a mapping cannot escape the selected destination directory.
old_ifs=$IFS
IFS=,
set -- $file_specs
IFS=$old_ifs
if [ "$#" -eq 0 ]; then
  printf 'At least one file is required\n' >&2
  exit 2
fi
artifacts=""
normalized_specs=""
seen_artifacts="|"
seen_outputs="|"
for spec in "$@"; do
  case "$spec" in
    *=*)
      file=${spec%%=*}
      output=${spec#*=}
      ;;
    *)
      file=$spec
      output=$spec
      ;;
  esac
  case "$file" in
    certificate.crt|chain.crt|fullchain.crt|private.key) ;;
    *) printf 'Unsupported file: %s\n' "$file" >&2; exit 2 ;;
  esac
  case "$output" in
    ""|.|..|*/*|*[!A-Za-z0-9._-]*)
      printf 'Invalid output filename: %s\n' "$output" >&2
      exit 2
      ;;
  esac
  case "$seen_artifacts" in
    *"|$file|"*) printf 'Duplicate artifact: %s\n' "$file" >&2; exit 2 ;;
  esac
  case "$seen_outputs" in
    *"|$output|"*) printf 'Duplicate output filename: %s\n' "$output" >&2; exit 2 ;;
  esac
  seen_artifacts="$seen_artifacts$file|"
  seen_outputs="$seen_outputs$output|"
  artifacts="${artifacts}${artifacts:+,}$file"
  normalized_spec="$file=$output"
  normalized_specs="${normalized_specs}${normalized_specs:+,}$normalized_spec"
done
file_specs=$normalized_specs

# Cron expressions are stored verbatim in the generated crontab. Reject shell
# metacharacters and require the traditional five-field format.
case "$schedule" in
  *[!A-Za-z0-9,'*/?_-\ ']*|*'
'*) printf 'Invalid cron schedule\n' >&2; exit 2 ;;
esac
set -f
set -- $schedule
set +f
if [ "$#" -ne 5 ]; then
  printf 'Cron schedule must contain five fields\n' >&2
  exit 2
fi

# Prefer a token supplied by automation, falling back to a non-echoing terminal
# prompt for an interactive installation.
token=${CERTVAULT_API_KEY-}
if [ -z "$token" ]; then
  if [ ! -r /dev/tty ]; then
    printf 'Set CERTVAULT_API_KEY when no interactive terminal is available\n' >&2
    exit 2
  fi
  printf 'CertVault API key: ' >/dev/tty
  stty -echo </dev/tty
  IFS= read -r token </dev/tty
  stty echo </dev/tty
  printf '\n' >/dev/tty
fi
if [ -z "$token" ]; then
  printf 'API key cannot be empty\n' >&2
  exit 2
fi

# The artifact set identifies a job. Reinstalling the same set intentionally
# replaces its destination, token, schedule, mappings, and reload command.
job=$(printf '%s-%s' "$certificate" "$artifacts" | tr -c 'A-Za-z0-9._-' '-')
config_dir=${CERTVAULT_CLIENT_CONFIG_DIR:-"$HOME/.config/certvault"}
script_dir=${CERTVAULT_CLIENT_SCRIPT_DIR:-"$HOME/.local/libexec"}
token_file="$config_dir/$job.token"
etag_dir="$config_dir/$job.etags"
sync_script="$script_dir/certvault-sync"
job_script="$script_dir/certvault-$job"

install -d -m 700 "$config_dir" "$script_dir" "$etag_dir"
if [ ! -d "$destination" ]; then
  install -d -m 755 "$destination"
fi
printf '%s\n' "$token" >"$token_file"
chmod 600 "$token_file"

# Requires Linux utilities: curl, tar, OpenSSL, flock, and mv with -T.
# Installing again replaces the job configuration. Discard validators from the
# previous configuration so the immediate sync populates a changed destination
# instead of treating its files as already current.
for file in certificate.crt chain.crt fullchain.crt private.key; do
  rm -f "$etag_dir/$file"
done
rm -f "$etag_dir/bundle"

sync_temporary=$(mktemp "$script_dir/.certvault-sync.XXXXXX")
cat >"$sync_temporary" <<'EOF'
@@SYNC@@

EOF
chmod 700 "$sync_temporary"
mv -f "$sync_temporary" "$sync_script"

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}


# Shared update state is scoped by server origin; API tokens remain job-local.
if [ "$auto_update" -eq 1 ]; then
  origin_id=$(printf '%s' "${server%/}" | openssl dgst -sha256 | awk '{print $NF}')
  client_dir="$script_dir/certvault-clients/$origin_id"
  update_config="$config_dir/client-updates/$origin_id"
  install -d -m 700 "$client_dir" "$update_config"
  exec 8>"$client_dir/update.lock"
  flock -x 8
  exec 7>"$client_dir/run.lock"
  flock -x 7
  if [ ! -s "$update_config/public.pem" ]; then
    pin_temporary=$(mktemp "$update_config/.public.XXXXXX")
    if ! curl --proto '=https' --proto-redir '=https' --connect-timeout 5 --max-time 20 --max-filesize 4096 -fsSL \
      "${server%/}/client/update/key.pem" -o "$pin_temporary" || \
      ! openssl pkey -pubin -in "$pin_temporary" -noout >/dev/null 2>&1; then
      rm -f "$pin_temporary"
      printf 'Unable to pin the client update public key\n' >&2
      exit 1
    fi
    chmod 600 "$pin_temporary"
    mv -f "$pin_temporary" "$update_config/public.pem"
  fi
  if [ ! -L "$client_dir/current" ]; then
    bootstrap=$(mktemp -d "$client_dir/version-bootstrap.XXXXXX")
    cp "$sync_script" "$bootstrap/sync.sh"
    cat >"$bootstrap/launcher.sh" <<'LAUNCHER'
@@LAUNCHER@@
LAUNCHER
    cat >"$bootstrap/update.sh" <<'UPDATER'
@@UPDATER@@
UPDATER
    chmod 700 "$bootstrap/launcher.sh" "$bootstrap/update.sh"
    ln -s "${bootstrap##*/}" "$client_dir/current"
  fi
  # A deliberate reinstall requests an immediate update check.
  printf '0\n' >"$update_config/next-check"
  exec 7>&-
  exec 8>&-
fi

# Persist a small wrapper with every value shell-quoted. Cron invokes this file
# rather than embedding credentials or complex arguments in the crontab.
{
  printf '#!/bin/sh\nexec '
  if [ "$auto_update" -eq 1 ]; then
    shell_quote "$client_dir/current/launcher.sh"
    printf ' '
    shell_quote "$client_dir"
    printf ' '
    shell_quote "$update_config"
  else
    shell_quote "$sync_script"
  fi
  printf ' '
  shell_quote "$token_file"
  printf ' '
  shell_quote "$server"
  printf ' '
  shell_quote "$certificate"
  printf ' '
  shell_quote "$destination"
  printf ' '
  shell_quote "$etag_dir"
  printf ' '
  shell_quote "$reload_command"
  old_ifs=$IFS
  IFS=,
  set -- $file_specs
  IFS=$old_ifs
  for spec in "$@"; do
    printf ' '
    shell_quote "$spec"
  done
  printf '\n'
} >"$job_script"
chmod 700 "$job_script"

# Replace this job's existing cron entry without disturbing unrelated entries.
marker="# certvault:$job"
existing=$(crontab -l 2>/dev/null || true)
{
  printf '%s\n' "$existing" | grep -Fv "$marker" || true
  printf '%s ' "$schedule"
  shell_quote "$job_script"
  printf ' %s\n' "$marker"
} | crontab -

"$job_script"
printf 'Installed CertVault sync job %s -> %s\n' "$job" "$destination"
